---
title: "Untitled"
author: "Antonio Ripoll"
date: "23 de mayo de 2020"
output: html_document
---
Hace scrapping de web YAENCONTRE.COM

REFOS DE SCRAPPING
```{r}
library(tidyverse)
library(rvest)
library(stringr)
url <- "https://www.yaencontre.com"
url2 <- "/venta/pisos/tarragona"

# sesión inicial en Rvest
ses_rvest1 <- html_session(url)
ses_rvest <- jump_to(ses_rvest1,url2)

# funcion de sacar datos
saca_Pagina <-function(ses_rvest){
  # Crea el data.frame
  nodos <-  html_nodes(ses_rvest, ".title.d-ellipsis.pointer")
  texto <- html_text(nodos)
  salida <- data.frame(pisos=str_trim(texto,side = "both"))
  
  item <- html_nodes(ses_rvest, ".ThinPropertiesList")
  uno=html_children(item)
  
  precios=list()
  habitaciones=list()
  banos=list()
  metros=list()
  texto=list()
  href=list()
  
  for(n in 1:length(uno)){
    if( html_name(uno[[n]])=="article"){
      buscado1=html_text(html_node(uno[[n]], ".price"))
      buscado1[is.na(buscado1)] <- "0"
      precios[length(precios)+1]= str_remove_all(buscado1,"[.\200]")
      
      buscado2=html_text(html_node(uno[[n]], ".icon-room"))
      buscado2[is.na(buscado2)] <- "0"
      habitaciones[length(habitaciones)+1]=buscado2
      
      buscado3=html_text(html_node(uno[[n]], ".icon-bath"))
      buscado3[is.na(buscado2)] <- "0"
      banos[length(banos)+1]=buscado3
      
      buscado4=html_text(html_node(uno[[n]], ".icon-meter"))
      buscado4[is.na(buscado4)] <- "0"
      metros[length(metros)+1]=str_sub(buscado4,1,-3)
      
      # Link de la pagina
      buscado5=html_attrs( html_nodes(uno[[n]],
                                      '[itemprop="url"]'))[[1]]["href"]
      href[length(href)+1]=buscado5
      
      # EXPERIMENTAL
      ###
      buscado6=html_attrs( html_nodes(uno[[n]],
                                      '[itemprop="url"]'))[[1]]["href"]
      newpage=jump_to( ses_rvest1,buscado6)
      extenso =html_text(html_node(newpage,".raw-format"))
      texto[length(texto)+1]=extenso
      ###
      # FIN EXPERIMENTAL
      
      
      

    }
  }
  salida$precios=unlist(precios)
  salida$habitaciones=unlist(habitaciones)
  salida$banos=unlist(banos)
  salida$metros=unlist(metros)
  salida$href=unlist(href)
  salida$texto=unlist(texto)
  return(salida)
}

# Numero de paginas
paginas=html_text(html_nodes(ses_rvest,".text-center.mt-md.mb-lg"))
paginas=as.numeric(strsplit(paginas," ")[[1]][3])

# acumulador de df. Saca la primera pagina
lista_DF <- saca_Pagina(ses_rvest)

# itero a lo largo de las paginas
for (i in 2:4) {
  print(i)
  url_n <- paste0("https://www.yaencontre.com/venta/pisos/tarragona","/pag-",
                as.character(i))
  Sys.sleep(1)
  ses_rvest_n <- html_session(url_n)
  pagina_i <- saca_Pagina(ses_rvest_n)
  lista_DF <-rbind(lista_DF,pagina_i)
}

Sys.sleep(1)
#ir cerrando las conexiones 
closeAllConnections()

  
```

Guarda los datos
```{r}
write.csv2(lista_DF,"E:/OTROS/POUMTORRE_1/R/Consulta_1/Pisos_Tarragona.csv",
          row.names = FALSE)

```


